title = "Hugo Split Gallery theme sample site"
copyright = "&copy;2021-2022 Me"
baseURL = "https://example.com"
languageCode = "en-us"
theme = "hugo-split-gallery"
themesDir = "../.."

DefaultContentLanguage = "en"

[taxonomies]
  location = "locations"
  season = "seasons"

[params]
  robots = "index, follow"
  favicon = ""
  description = "Photo gallery inspired by Hugo Split Theme"
  images = ["DSCF0348.jpg"]
  # customCss = ['css/custom1.css', 'css/custom2.css']
  # customJs = ['js/custom1.js', 'js/custom2.js']
  # enableDownloadAll = false
  footnote = "Foo bar"
  includeOriginalImage = false
  # largeImageSize = "2000x"
  # siteLogo = ""
  # useDefaultColors = true
  # useDefaultFonts = true
  galleryLoop = true
  # galleryCounter = true
  # galleryButtons = ["zoom", "slideShow", "close"]
  # galleryAnimationEffect = "zoom"
  # galleryAnimationDuration = 366
  # galleryTransitionEffect = "fade"
  # galleryTransitionDuration = 366
  # gallerySlideshowSpeed = 3000
  # sharedMediaBundle = "/media"
  showTranslations = true
  map2gpx = "en"
  paginate = 10

  [params.taxonomies]
    [params.taxonomies.locations]
      icon = "location-arrow"
    [params.taxonomies.seasons]
      icon = "calendar"

[languages]
  [languages.en]
    weight = 1

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About this theme"
        pre = "<i class='fa fa-heart'></i>"
        url = "/about/"
        weight = -110

      [[languages.en.menu.main]]
        name = "Getting started"
        pre = "<i class='fa fa-road'></i>"
        url = "/getting-started/"
        weight = -100

  [languages.fr]
    title = "Site exemple du thème Hugo Split Gallery"
    languageCode = "fr-fr"
    showTranslations = false
    map2gpx = "fr"
    weight = 2

    [languages.fr.params]
      description = "Gallerie photo inspirée de Hugo Split Theme"
